CFLAGS=	-ansi

Caverage.exe:	Caverage.c
				gcc $(CFLAGS) Caverage.c -o Caverage.exe
				
Ccp.exe:	Ccp.c
			gcc $(CFLAGS) Ccp.c -o Ccp.exe
			
Ccat.exe:	Ccat.c
			gcc $(CFLAGS) Ccat.c -o Ccat.exe

Cwc.exe:	Cwc.c
			gcc $(CFLAGS) Cwc.c -o Cwc.exe

Csort.exe:	Csort.c
			gcc $(CFLAGS) Csort.c -o Csort.exe
			
all: Caverage.exe Ccp.exe Ccat.exe Cwc.exe Csort.exe
